name: Deploy Packages
on:
  workflow_dispatch:
    inputs:
      package:
        description: The package to publish
        required: true
        type: string

jobs:
  # A separate release build that is only run for commits that are the result of merging the "Version Packages" PR
  # We can't re-use the output from the above step, but we'll have a guaranteed node_modules cache and
  # only run the build steps that are necessary for publishing
  release:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      CI: 'true'
      NODE_OPTIONS: --max-old-space-size=8192

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/ # Needed for auth
      - name: yarn install
        uses: backstage/actions/yarn-install@772cef06641090d0095188e15c85647acdf0c250 # v0.6.11
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: build type declarations
        run: yarn tsc:full

      - name: build package
        run: yarn workspace ${{ inputs.package }} build

      # Publishes current version of packages that are not already present in the registry
      - name: publish
        run: |
          yarn config set -H 'npmAuthToken' "${{secrets.GITHUB_TOKEN}}"
          yarn workspace ${{ inputs.package }} npm publish --access public --tolerate-republish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
