name: Deploy Packages
on:
  workflow_dispatch:
    inputs:
      package:
        description: The package to publish
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v2

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/ # Needed for auth

      - name: yarn install 
        run: |
          YARN_CHECKSUM_BEHAVIOR=update yarn
          yarn install

      - name: build type declarations
        run: yarn tsc:full

      - name: build package
        run: yarn workspace ${{ inputs.package }} build

      # Publishes current version of packages that are not already present in the registry
      - name: publish
        run: |
          yarn config set -H 'npmAuthToken' "${{secrets.GITHUB_TOKEN}}"
          yarn workspace ${{ inputs.package }} npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
