name: Deploy Packages
on:
  workflow_dispatch:
    inputs:
      package:
        description: The package to publish
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      CI: true
      NODE_OPTIONS: ${{ matrix.node-version == '20.x' && '--max-old-space-size=8192 --no-node-snapshot' || '--max-old-space-size=8192' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/ # Needed for auth

      - name: update yarn.lock
        run: YARN_CHECKSUM_BEHAVIOR=update yarn

      - name: yarn install
        uses: backstage/actions/yarn-install@25145dd4117d50e1da9330e9ed2893bc6b75373e # v0.6.15
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: backstage-cli cache
        uses: actions/cache@v4
        with:
          path: .cache/backstage-cli
          key: ${{ runner.os }}-v${{ matrix.node-version }}-backstage-cli-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-v${{ matrix.node-version }}-backstage-cli-

      - name: type checking and declarations
        run: yarn tsc:full

      - name: build package
        run: yarn workspace ${{ inputs.package }} build

      # Publishes current version of packages that are not already present in the registry
      - name: publish
        run: |
          yarn config set -H 'npmAuthToken' "${{secrets.GITHUB_TOKEN}}"
          yarn workspace ${{ inputs.package }} npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
